alias init="cmake -H. -Bbuild"
alias initdbg="cmake -DCMAKE_BUILD_TYPE=Debug -H. -Bbuild"
alias build="cmake --build build"
alias clean="rm -rf build"
alias segmentation="build/segmentation tree.off"
alias parameterize="build/parameterize tree.off"
alias debug="lldb -or -- build/parameterize tree.off"
